"""create projects table

Revision ID: 680a7c47a7ff
Revises: f3f70fb38b10
Create Date: 2021-10-30 14:22:25.156372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680a7c47a7ff'
down_revision = 'f3f70fb38b10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_url_name'), 'projects', ['url_name'], unique=True)
    op.add_column('programming_languages', sa.Column('url_name', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_programming_languages_url_name'), 'programming_languages', ['url_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_programming_languages_url_name'), table_name='programming_languages')
    op.drop_column('programming_languages', 'url_name')
    op.drop_index(op.f('ix_projects_url_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
