"""stacks

Revision ID: f3f70fb38b10
Revises: aae63862196e
Create Date: 2021-10-30 14:11:24.251590

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3f70fb38b10'
down_revision = 'aae63862196e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programming_languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('choices')
    op.drop_index('ix_technologies_url_name', table_name='technologies')
    op.drop_table('technologies')
    op.drop_index('ix_projects_url_name', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('projects_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='projects_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_projects_url_name', 'projects', ['url_name'], unique=False)
    op.create_table('technologies',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('technologies_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('url_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='technologies_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_technologies_url_name', 'technologies', ['url_name'], unique=False)
    op.create_table('choices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('technology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='choices_project_id_fkey'),
    sa.ForeignKeyConstraint(['technology_id'], ['technologies.id'], name='choices_technology_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='choices_pkey')
    )
    op.drop_table('programming_languages')
    # ### end Alembic commands ###
